import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Header } from "@/components/header";
import { WalletProvider } from "@/components/wallet-provider";
import { Kanit} from 'next/font/google';
import { BackgroundBeams } from "@/components/aceternity/background-beams";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = Kanit({
  subsets: ['latin'],
  variable: '--font-kanit',
  weight: ['300', '400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased bg-background dark`}
      >
        <WalletProvider>
            <div className="relative min-h-screen">
            <BackgroundBeams />
            <Header />
            <div className="isolate">
                {children}
            </div>
            </div>
        </WalletProvider>
      </body>
    </html>
  );
}
